version: 2
jobs:
  build:
    context: sonar
    docker:
      - image: circleci/node:7.10

    environment:
        PROJECT_VERSION: ""

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install
      - run: sudo npm i -g sonarqube-scanner
      - run: echo export PROJECT_VERSION=$(node -e "console.log(require('./package.json').version);")
      - run: PROJECT_VERSION=$(node -e "console.log(require('./package.json').version);")

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: 
          name: build
          command: npm run build
      - store_artifacts:
          path: .coverage/unit/
          prefix: coverage
      - store_test_results:
          path: .testresults/unit
      - run: echo $PROJECT_VERSION
      - run:
          name: sonar
          command: sonar-scanner -Dsonar.projectVersion=$(node -e "console.log(require('./package.json').version);") -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONARCLOUD_TOKEN
