trigger:
  - master

pr:
  - master

pool:
  vmImage: 'windows-2019'

resources:
  repositories:
    - repository: templates
      type: github
      name: swellaby/azure-pipelines-templates
      endpoint: swellaby

steps:
  - script: |
      npm install -g npm@6.11.1
      npm run prepare - successful
    displayName: 'Temp npm version set'

  - template: '../steps/run-tests.yml'
    parameters:
      envName: 'Windows'
