trigger:
- master

pr:
- master

pool:
  vmImage: 'vs2019-win2016'

resources:
  repositories:
  - repository: templates
    type: github
    name: swellaby/azure-pipelines-templates
    endpoint: swellaby

steps:
- template: '../steps/run-tests.yml'
  parameters:
    envName: 'Windows'
